# Site settings
title:          Sudip Ghosh
description:    "I'm an Indie Maker."
baseurl:        ""
url:            "https://sudip365.github.io"

# Author
author:
  name:         Sudip Ghosh
  url:          https://sudip365.github.io
  email:        sudipghosh.online@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
